# Makefile to compile UMIX Programming Assignment 2 (pa2) [updated 12/20/19]

LIBDIR = $(UMIXPUBDIR)/lib

CC 	= cc 
FLAGS 	= -g -L$(LIBDIR) -lumix2

PA2 =	pa2a pa2b pa2c

pa2:	$(PA2)

pa2a:	pa2a.c aux.h umix.h mycode2.o
	$(CC) $(FLAGS) -o pa2a pa2a.c mycode2.o

pa2b:	pa2b.c aux.h umix.h mycode2.o
	$(CC) $(FLAGS) -o pa2b pa2b.c mycode2.o

pa2c:	pa2c.c aux.h umix.h mycode2.o
	$(CC) $(FLAGS) -o pa2c pa2c.c mycode2.o

mycode2.o:	mycode2.c aux.h sys.h mycode2.h
	$(CC) $(FLAGS) -c mycode2.c

clean:
	rm -f *.o $(PA2)
